

sudo: false
dist: trusty
language: bash
services: docker

script:
    - make -C wheels && git diff --exit-code
    - .ci/check_wheels.py wheels/

# runs independent of 'script' failure/success
#after_script:
    #- ${DOCKER_RUN} /src/.ci/travis/after_script.bash

notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never

branches:
  except:
    - gh-pages
